[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["cbindgen"]

[tasks.test]
clear = true

[tasks.release]
command = "cargo"
args = ["build", "-r"]
dependencies = ["cbindgen"]

[tasks.cbindgen]
install_crate = { crate_name = "cbindgen" }
command = "cbindgen"
args = ["-o", "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/include/meu3.h"]

[tasks.clean]
command = "cargo"
args = ["clean"]
